/*
 * (c) 2024 Francis McNamee
 * */
 
package ie.francis.pg.printer;

import ie.francis.pg.Production;
import ie.francis.pg.Version;
import ie.francis.pg.term.NonTerminal;
import ie.francis.pg.term.Optional;
import ie.francis.pg.term.Plus;
import ie.francis.pg.term.Star;
import ie.francis.pg.term.Term;
import ie.francis.pg.term.Terminal;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class JavaPrinter extends BasePrinter implements Printer {

  public JavaPrinter(Production... productions) {
    super(productions);
  }

  @Override
  public String print() {

    cp.append(String.format("/* Generated by pg v%s */\n\n", Version.VERSION_STRING));
    cp.append("class Parser {\n\n");

    depth++;

    cp.append(String.format("%sParser() {\n", StringUtil.indent(depth)));
    cp.append("\n");
    cp.append(String.format("%s}\n", StringUtil.indent(depth)));
    cp.append("\n");

    cp.append(String.format("%spublic void parse() {\n", StringUtil.indent(depth)));
    depth++;
    NonTerminal firstNonTerminal = new ArrayList<>(this.productions.keySet()).get(0);
    cp.append(String.format("%s\n", print(firstNonTerminal)));
    depth--;
    cp.append(String.format("%s}\n", StringUtil.indent(depth)));
    cp.append("\n");

    for (Map.Entry<NonTerminal, List<Production>> entry : this.productions.entrySet()) {
      NonTerminal nonTerminal = entry.getKey();
      List<Production> productions = entry.getValue();

      cp.append(
          String.format(
              "%s// %s : %s\n",
              StringUtil.indent(depth), productions.get(0).nonTerminal(), productions.get(0)));
      for (int i = 1; i < productions.size(); i++) {
        Production production = productions.get(i);
        cp.append(
            String.format(
                "%s// %s | %s\n",
                StringUtil.indent(depth),
                StringUtil.indent(production.nonTerminal().name().length(), ' '),
                production));
      }
      cp.append(
          String.format("%sprivate void %s() {\n\n", StringUtil.indent(depth), nonTerminal.name()));
      StringBuilder ifBuilder = new StringBuilder();

      if (productions.size() == 1) {
        List<Term> terms = productions.get(0).terms();
        for (Term term : terms) {
          depth++;
          cp.append(String.format("%s\n", print(term)));
          depth--;
        }
      } else {
        depth++;
        cp.append(String.format("%s", StringUtil.indent(depth)));
        for (int i = 0; i < productions.size(); i++) {
          StringBuilder ifConditionBuilder = new StringBuilder();
          List<String> first = new ArrayList<>(predict(productions.get(i)));
          for (int j = 0; j < first.size(); j++) {
            if (!first.get(j).equals("Ɛ")) {
              ifConditionBuilder.append(String.format("nextTokenIs(%s)", first.get(j)));
              if (j + 1 < first.size()) {
                ifConditionBuilder.append(" || ");
              }
            }
          }

          ifBuilder.append(String.format("if (%s) {\n", ifConditionBuilder));

          List<Term> terms = productions.get(i).terms();
          for (Term term : terms) {
            depth++;
            ifBuilder.append(String.format("%s\n", print(term)));
            depth--;
          }

          if (i + 1 < productions.size()) {
            ifBuilder.append(String.format("%s} else ", StringUtil.indent(depth)));
          } else {
            ifBuilder.append(String.format("%s}\n\n", StringUtil.indent(depth)));
          }
        }
        depth--;

        cp.append(ifBuilder);
      }
      cp.append(String.format("%s}\n\n", StringUtil.indent(depth)));
    }

    cp.append(
        String.format("%sprivate boolean nextTokenIs(Token token) {\n", StringUtil.indent(depth)));
    depth++;
    cp.append(
        String.format(
            "%sreturn scanner.peek().type() == token.type();\n", StringUtil.indent(depth)));
    depth--;
    cp.append(String.format("%s}\n", StringUtil.indent(depth)));
    cp.append("\n");

    depth--;
    cp.append("}\n");

    return cp.toString();
  }

  @Override
  public String print(Optional optional) {
    StringBuilder sb = new StringBuilder();

    StringBuilder ifConditionBuilder = new StringBuilder();
    Term first = optional.expand().get(0);
    Set<String> firstSet = new LinkedHashSet<>();
    firstSet.add(first.toString());
    if (first instanceof NonTerminal) {
      firstSet = predict((NonTerminal) first);
    }

    List<String> firstList = new ArrayList<>(firstSet);
    for (int i = 0; i < firstList.size(); i++) {
      if (!firstList.get(i).equals("Ɛ")) {
        ifConditionBuilder.append(String.format("nextTokenIs(%s)", firstList.get(i)));
        if (i + 1 < firstList.size()) {
          ifConditionBuilder.append(" || ");
        }
      }
    }

    sb.append(String.format("%sif (%s) {\n", StringUtil.indent(depth), ifConditionBuilder));
    for (Term term : optional.terms()) {
      depth++;
      sb.append(String.format("%s\n", print(term)));
      depth--;
    }
    sb.append(String.format("%s}\n", StringUtil.indent(depth)));
    return sb.toString();
  }

  @Override
  public String print(Plus plus) {
    StringBuilder sb = new StringBuilder();

    StringBuilder doWhileConditonBuilder = new StringBuilder();
    Term first = plus.expand().get(0);
    Set<String> firstSet = new LinkedHashSet<>();
    firstSet.add(first.toString());
    if (first instanceof NonTerminal) {
      firstSet = predict((NonTerminal) first);
    }

    List<String> firstList = new ArrayList<>(firstSet);
    for (int i = 0; i < firstList.size(); i++) {
      if (!firstList.get(i).equals("Ɛ")) {
        doWhileConditonBuilder.append(String.format("nextTokenIs(%s)", firstList.get(i)));
        if (i + 1 < firstList.size()) {
          doWhileConditonBuilder.append(" || ");
        }
      }
    }

    sb.append(String.format("%sdo {\n", StringUtil.indent(depth)));

    for (Term term : plus.terms()) {
      depth++;
      sb.append(String.format("%s\n", print(term)));
      depth--;
    }

    sb.append(String.format("%s} while (%s);\n", StringUtil.indent(depth), doWhileConditonBuilder));
    return sb.toString();
  }

  @Override
  public String print(Star star) {
    StringBuilder sb = new StringBuilder();

    StringBuilder whileConditonBuilder = new StringBuilder();
    Term first = star.expand().get(0);
    Set<String> firstSet = new LinkedHashSet<>();
    firstSet.add(first.toString());
    if (first instanceof NonTerminal) {
      firstSet = predict((NonTerminal) first);
    }

    List<String> firstList = new ArrayList<>(firstSet);
    for (int i = 0; i < firstList.size(); i++) {
      if (!firstList.get(i).equals("Ɛ")) {
        whileConditonBuilder.append(String.format("nextTokenIs(%s)", firstList.get(i)));
        if (i + 1 < firstList.size()) {
          whileConditonBuilder.append(" || ");
        }
      }
    }

    sb.append(String.format("%swhile (%s) {\n", StringUtil.indent(depth), whileConditonBuilder));
    for (Term term : star.terms()) {
      depth++;
      sb.append(String.format("%s\n", print(term)));
      depth--;
    }
    sb.append(String.format("%s}\n", StringUtil.indent(depth)));
    return sb.toString();
  }

  @Override
  public String print(Terminal terminal) {
    return String.format("%sscanner.next();", StringUtil.indent(depth));
  }

  @Override
  public String print(NonTerminal nonTerminal) {
    return String.format("%s%s();", StringUtil.indent(depth), nonTerminal.name());
  }

  @Override
  public String printNonTerminalBody() {
    return "";
  }

  @Override
  public String print(Term term) {
    if (term instanceof NonTerminal) {
      return print((NonTerminal) term);
    } else if (term instanceof Terminal) {
      return print((Terminal) term);
    } else if (term instanceof Optional) {
      return print((Optional) term);
    } else if (term instanceof Plus) {
      return print((Plus) term);
    } else if (term instanceof Star) {
      return print((Star) term);
    }
    return null;
  }
}
